# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  api:
    image: reactioncommerce/reaction:3.9.0
    env_file:
      - ./.env
    networks:
      default:
      reaction:
    ports:
      - "3000:3000"
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:3000/}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3  
    restart: always

  mongo:
    image: mongo:4.2.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    networks:
      default:
      reaction:
    ports:
      - "27017:27017"
    volumes:
      - mongo-db4:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/reaction --quiet
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
  

  migration:
    image: reaction-api-migrations:latest
    depends_on: 
      - mongo
    env_file:
      - ./.env
    networks: 
      default:
      reaction:

volumes:
  mongo-db4:
